### ISSUE TITLE
Adding JPA support

### ISSUE THREAD

**Issue by antoinesd** [swarmic/swarmic#6]
Adding persistence support with JPA and probably hibernate to start.

**Comment by antoinesd** [comment]
hi @johnament, I take a look at the work you did on your branch and I wonder what is the interest of using DeltaSpike JPA module here. With narayana support and JTA 1.2 we have the standard @Transactional interceptor. Hibernate knows how to retrieve transactionmanager from Narayana if the matching classes are discovered (https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/StandardJtaPlatformResolver.java#L50)
What are the other benefits ?

**Comment by johnament** [comment]
So there's two main benefits that I see.

- `@PersistenceContext` based injection doesn't work, since its an EJB mandate, not a CDI mandate.  DS introduces an equivalent version.
- Demoing something like repository support is going to be huge for us.  Its one area where another project gets huge boosts.

The only thing I'm left figuring out is why I need to manually start the transaction.  That should be taken care of.  I was going to do it last night, but got stuck on a different issue.  Definitely will have time this evening to resolve.

**Comment by antoinesd** [comment]
> - `@PersistenceContext` based injection doesn't work, since its an EJB mandate, not a CDI mandate.  DS introduces an equivalent version.

Good point. This said, we could have start by a simple producer instead of getting code parsing `persistence.xml`. Weld has a (priorietary) interface that allows that too: https://github.com/antoinesd/weld-api/blob/7d012e76ca6be51ba4f9785d83c57e6420832161/weld-spi/src/main/java/org/jboss/weld/injection/spi/JpaInjectionServices.java

> - Demoing something like repository support is going to be huge for us.  Its one area where another project gets huge boosts.

Totally agree here, but it's a more advance usage and we should make it shine independetly of JPA support to avoid confusion IMO.
My point is not to avoid Deltaspike (date module is clearly a must have) but to have it optional for small needs.

> The only thing I'm left figuring out is why I need to manually start the transaction.  That should be taken care of.  I was going to do it last night, but got stuck on a different issue.  Definitely will have time this evening to resolve.

Do you need help on this part ?

**Comment by antoinesd** [comment]
@johnament I rebased this branch (localy) on the last master to get the new maven architecture. Let me know if you want me to push it. It could save you time.
